from random import choice

error_404 = [
    "Ooops! Něco se ztratilo v akci.",
    "Tato stránka neexistuje. Buď se odkaz pokazil nebo jste zabloudili.",
    "Tato stránka je jako sníh v létě - neexistuje.",
    "Chyba 404: Stránka nebyla nalezena, ale zvedněte hlavu, stále máte šanci na nápravu.",
    "Toto místo je tak tajné, že ani neexistuje. Ovšem, jestli tu chcete zůstat, to je na vás.",
    "Když hledáte význam života, určitě ho tady nenajdete.",
    "Toto místo bylo ukradeno piráty. Někdy se vrátí, někdy ne.",
    "Máte špatnou adresu? Hledal jste opravdu vtipný obrázek kočky?",
    "Chcete objevit nové světy a nové civilizace? Bohužel, tady se to nedá.",
    "Chyba 404 - Neviditelná stránka. Prosím, nedívejte se na ni.",
    "Toto místo bylo sestřeleno, stejně jako vaše naděje na to, že zde něco najdete.",
    "Chyba 404 - A jaké to má být? Já taky nevím.",
    "Omlouváme se, tato stránka byla prohlášena za ztracenou a není hledána.",
    "V této tmě je těžké najít cestu. A tato stránka je jako temný tunel, který nevede nikam.",
    "Tato stránka byla přesunuta do archivu. Pokud jste se sem dostali náhodou, tak jste v archivu úplně špatně.",
    "Chyba 404: Vypadá to, že jste se ztratili. Pokud se nevrátíte do 5 minut, budeme vysílat záchranný tým.",
    "Tato stránka je jako prázdná krabice, neobsahuje nic, co by vám pomohlo dál.",
    "Opravdu jste tohle chtěli? Je to stejně neúspěšné jako pokus o to naučit kočku číst.",
    "Klidně si zde odpočiňte. Tato stránka je stejně užitečná jako spící dřevo.",
    "Chyba 404 - Toto místo bylo pohlceno černou dírou. Prosím, pokračujte na vlastní nebezpečí.",
    "Tato stránka není k nalezení. Ale jestli chcete, můžeme vám nabídnout dnešní speciální - prázdnou stránku.",
    "Chyba 404: Tuto stránku získala gravitace a nyní se nachází mimo dosah.",
    "Tohle místo je stejně prázdné jako můj život.",
    "Tuto stránku bohužel nenašel ani Google. Takže se asi nemáte na co těšit.",
    "Chyba 404: Zde není nic. Jako vlastně v celém vesmíru.",
    "Tato stránka je jako jehla v kupce sena. Bohužel, nemáme ani kupku sena.",
    "Tato stránka je jako prázdná bedna od whisky. Zdá se, že tu chybí něco podstatného.",
    "Chyba 404: Vypadá to, že jste se ztratili. Nebo se to možná stalo s touto stránkou.",
    "Toto místo bylo pohlceno temnotou. Stejně jako vaše naděje na nalezení obsahu.",
]

error_401 = [
    "Omlouváme se, ale abyste mohli pokračovat, musíte mít více kreditů.",
    "Tato stránka je stejně zabezpečená jako bezpečný pokoj s návnadou.",
    "Chyba 401: Tato stránka je tak tajná, že si o ní ani ona sama neví.",
    "Bez správných oprávnění se tady nic neděje. Tento web je jako uzavřená dveře do školy v neděli.",
    "Vypadá to, že jste nezískali přístupový klíč. Ale nebojte, můžete si ho koupit na trhu s černým trhem.",
    "Chyba 401: Tento web je tak vysoké zabezpečení, že má více hesel než já.",
    "Tato stránka je jako balíček dýmu - můžete se k ní přiblížit, ale nikdy se nedozvíte, co je v ní uvnitř.",
    "Bohužel, bez správných klíčů nemůžete otevřít dveře. A tato stránka je jako dveře do tajného bunkru.",
    "Tato stránka je jako když se pokoušíte dostat do nejlepšího klubu ve městě bez VIP karty. Není šance.",
    "Chyba 401: Pokud se snažíte dostat na tuto stránku, budete potřebovat více než jen velmi pevné heslo. Potřebujete i štěstí.",
    "Chyba 401: Tato stránka je tak tajná, že by vám ani nepověděla, že vám to řekla.",
    "Tato stránka je jako tajná služba - bez správných průkazů se nebudete moc dostat nikam.",
    "Toto místo je jako vstup do banky - bez správných kódů nemáte šanci.",
    "Chyba 401: Tato stránka je stejně chráněná jako želva ve své ulitě.",
    "Omlouváme se, ale tuto stránku si můžete prohlédnout pouze v zapadlém baru v opuštěné čtvrti.",
    "Tato stránka je jako klub pro VIP členy. Pokud nejste na seznamu, nemáte šanci.",
    "Chyba 401: Tuto stránku jsme zamkli a klíč hodili do západního Pacifiku.",
    "Toto místo je stejně tajné jako to, co se skrývá na dně Vašeho batohu.",
    "Tato stránka je jako tajná agentura. Pokud nemáte správné heslo, nebudete moci pokračovat.",
    "Chyba 401: Tuto stránku chrání heslo, které má více znaků než chystaný scénář filmu Válka světů.",
    "Tato stránka je tak bezpečná, že mě překvapuje, že jste se vůbec dostali na adresu URL.",
    "Bez správného hesla je tato stránka méně přístupná než zákulisí opery.",
    "Chyba 401: Tuto stránku nenajdete ani v GPS navigaci.",
    "Toto místo je jako poklad na konci duhy, ale bez správných oprávnění budete muset pokračovat dál.",
    "Tato stránka je jako hra o trůny - kdo neovládá správné heslo, nemá šanci na přístup.",
    "Chyba 401: Tato stránka je jako já, když se snažím najít ztracený klíček - není nikde.",
    "Bez správných oprávnění se tady nic neděje. Toto místo je jako tajné útočiště zeměkoule.",
    "Tato stránka je stejně dobře skrytá jako moje dávno zapomenuté heslo.",
    "Chyba 401: Pokud se snažíte získat přístup na tuto stránku, budete potřebovat více než jen štěstí.",
    "Tato stránka je tak bezpečná, že se budete muset stát součástí její obrany, abyste se na ni dostali.",
]

error_403 = [
    "Omlouváme se, ale tato stránka je jako brána do pekla - nepovolený vstup!",
    "Bez správných oprávnění se na této stránce nedá nic dělat. Je to jako snažit se otevřít dveře se špatným klíčem.",
    "Tato stránka je tak tajná, že ani žádný z proroků nedokáže předpovědět, co se za ní skrývá.",
    "Chyba 403: Tato stránka je tak chráněná, že má více zabezpečení než Fort Knox.",
    "Tato stránka je jako bezpečné místo - pokud nemáte správné karty, nepustí vás ani dovnitř.",
    "Chyba 403: Pokud se snažíte dostat na tuto stránku, budete potřebovat více než jen heslo. Budete potřebovat i dobrou náladu.",
    "Bez správných oprávnění tady nic neuděláte. Je to jako snažit se dostat do soukromého klubu bez pozvání.",
    "Tato stránka je stejně tajná jako tajná zbraň Jamese Bonda.",
    "Chyba 403: Tato stránka je tak bezpečná, že musíte mít tři různé typy ověření, abyste se na ni dostali.",
    "Tato stránka je jako zámek na hradě - bez správného klíče se nedostanete dál.",
    "Tato stránka je tak přístupná jako parkoviště na Black Friday.",
    "Chyba 403: Tato stránka je tak tajná, že ani v kódovacím klíči ji nenajdete.",
    "Tato stránka je jako schovka - bez správných oprávnění ji nenajdete.",
    "Bez správného hesla se na této stránce nemůžete dostat ani s pomocí mapy pokladů.",
    "Tato stránka je jako exkluzivní noční klub - bez VIP karty se sem nedostanete.",
    "Chyba 403: Tuto stránku chrání víc než státní tajemství.",
    "Tato stránka je tak tajná, že i Chuck Norris se sem nedostane bez správného hesla.",
    "Bez správných oprávnění tady zůstanete na mrtvém bodě. Je to jako v obchodě s potravinami bez peněženky.",
    "Tato stránka je jako oblíbená televizní show - bez správných oprávnění ji nemůžete sledovat.",
    "Chyba 403: Tato stránka je tak chráněná, že si na ni budete muset s sebou nosit svůj vlastní klíč k srdci.",
    "Bez správných oprávnění se na této stránce nedá nic dělat. Je to jako snažit se vystartovat raketu bez klíče.",
    "Chyba 403: Tato stránka je jako velvyslanectví, kde bez správného diplomatického pasu nemáte šanci.",
    "Tato stránka je tak tajná, že ani věštci vám o ní neřeknou ani slovo.",
    "Bez správných oprávnění se na této stránce nedostanete ani s pomocí čarodějnické hůlky.",
    "Tato stránka je jako knihovna, kde bez čtenářského průkazu se nedostanete k žádné knize.",
    "Chyba 403: Tuto stránku si můžete prohlédnout pouze přes okno - bez správných oprávnění nemáte přístup.",
    "Tato stránka je tak bezpečná, že je snadnější se dostat do Fort Boyardu než sem.",
    "Bez správných oprávnění se na této stránce nedostanete ani s pomocí Batmobila.",
    "Tato stránka je jako pokoj plný drahokamů, ale bez správných oprávnění se k nim nedostanete.",
    "Chyba 403: Tuto stránku chrání více zabezpečení než laboratoře na Area 51.",
]

error_time = [
    "Vypadá to, že jste zabloudili, jako v křoví uvnitř DeLoreana. Přidáme to na seznam věcí, které je třeba vymyslet.",
    "Nastavili jste si stroj času na špatné datum. Tato stránka se zřejmě ještě nenarodila.",
    "Omlouváme se, zdá se, že jste dorazili do místnosti plné prázdných počítačových obrazovek. Zkuste to znovu za pár let!",
    "Je nám líto, ale tato stránka je mimo dosah. Možná to bude lepší, když se budete držet přítomnosti.",
    "Vypadá to, že jste se dostali do časové smyčky a narazili na stránku, která ještě neexistuje. Pro zbytek cesty následujte nápis 'výstup'.",
    "Omlouváme se, ale zdá se, že jste narazili na něco, co neexistuje. Měli byste se vrátit na pevnou půdu, než se zaseknete v časoprostoru.",
    "Tato stránka je mimo dosah, jako je plánování dovolené v roce 2020.",
    "Vypadá to, že jste nás zatím předběhli. Vracet se zpět do budoucnosti je někdy těžké.",
    "Je nám líto, ale zdá se, že se ocitnete na stránce, která nikdy neexistovala. Snad to nevypadá jako paradox.",
    "Tato stránka je mimo dosah, jako obchod s videokazetami v roce 2022.",
    "Omlouváme se, zdá se, že jste dorazili do místa, kde čas a prostor neexistují. Vraťte se zpět, než se věci zvrhnou.",
    "Tuto stránku nelze nalézt, jako pravděpodobnost, že by t-Rex dokázal řídit auto.",
    "Vypadá to, že jste ztratili cestu, jako dinosaur v moderním světě. Zkuste to znovu za pár milionů let!",
    "Je nám líto, ale tato stránka je mimo dosah, jako prodej ledniček v Arktidě.",
    "Tato stránka není k nalezení, jako ztracená loď v Bermudském trojúhelníku.",
    "Omlouváme se, zdá se, že jste dorazili do jiné dimenze. Tato stránka zde neexistuje.",
    "Vypadá to, že jste zabloudili v časoprostoru. Vraťte se zpět, než se stanete obětí časového paradoxu.",
    "Omlouváme se, tato stránka není k nalezení, jako nejlepší pizza mimo Itálii.",
    "Tuto stránku nelze najít, jako člověka bez mobilního telefonu v 21. století.",
    "Je nám líto, zdá se, že jste dorazili na místo, kde se nachází jen věčné nic. Raději se vraťte na hlavní stránku!",
]

def error_page_joke(error_code):
    if error_code == "401":
        error = choice(error_401)
    elif error_code == "403":
        error = choice(error_403)
    elif error_code == "404":
        error = choice(error_404)
    elif error_code == "time":
        error = choice(error_time)
    return error